site_name: Películas
nav:
    - Inicio: 'index.md'
    - Baby Driver: 'babydriver.md'
    - El juego de Ender: 'juegoender.md'
    - Spiderman: Lejos de casa: 'spiderman.md'
theme:
    name: readthedocs
copyright: Hecho por Albert Chao Vasco.
